spring:
  application:
    name: currency-exchange-service
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/currency-exchange-service?useSSL=true&characterEncoding=utf8
    username: root
    password: 123456
server:
  port: 8000
